Business engineering 2
haru248/mokumoku pull request #2
Opened 2023-01-26 07:03 UTC by haru248

# 選択した事業
1.サービス登録者数の内、男性60%に対して、女性は40%。一方で、サービス内のもくもく会に参加した人の比率は、男性90%：女性10%と大きな差が出ています。もっと女性が使いやすいようなサービス設計にする必要があるのではないか？

# 概要
【実装方針】
- ユーザー登録時に手入力やチェックボックス入力ではなく、セレクト形式で性別登録できる。
- イベント作成画面にOnly womanのチェックボックスにチェックを入れるだけで女性限定イベントを作できる。
- ユーザーが女性以外の場合、イベント作成時にOnly womanは表示されず、女性限定イベントが作成できない。
- 女性限定イベントには女性のみが参加できる。
- 女性以外の場合、女性限定イベントの詳細ページを開いた際に「このもくもく会に参加する」が表示されない。
- 女性限定イベントは一覧・詳細画面にて「女性限定」が表記される。

【注意点】
- イベントが女性限定であるかを判定するカラムは"only_woman"とする
- ユーザーの性別登録のカラムは"gender"とする
- ユーザー登録時の性別のセレクト部分はenumを使って「その他・男性・女性」が表示される（その際に特に操作が無かれば"その他"が選択される）
    
【Gemfile】
Testグループに以下のgemを追加
- gem 'capybara', '~> 3.23'
- gem 'selenium-webdriver'
- gem 'webdrivers' 

# テスト結果
[![Image from Gyazo](https://i.gyazo.com/5b4c3031f996dc838d2994f882e0560d.png)](https://gyazo.com/5b4c3031f996dc838d2994f882e0560d)

2023-01-26 10:45 UTC, busitora requested changes
細かいですがよろしくおねがいします

2023-01-26 10:45 UTC, busitora commented on app/views/events/show.html.erb
> +                  <% if !@event.only_woman || @event.only_woman && current_user.woman? %>
可読性がにかけるので、モデル等にメソッド移す＆viewから見た時にぱっと分かる命名にしてください！

2023-01-26 10:45 UTC, busitora commented on spec/rails_helper.rb
> +
無駄な空白

2023-01-27 07:10 UTC, haru248 commented on spec/rails_helper.rb
> +
[25b7e93](https://github.com/haru248/mokumoku/pull/2/commits/25b7e935a740f66c05326ca65fe54efb4dd6858c)で修正しました

2023-01-27 07:13 UTC, haru248 commented on app/views/events/show.html.erb
> +                  <% if !@event.only_woman || @event.only_woman && current_user.woman? %>
[5e5046a](https://github.com/haru248/mokumoku/pull/2/commits/5e5046ad277cd821a9da735d64e7351c66845661)で処理を`event.rb`に移動、メソッド名を `only_woman_event?`に修正しました

2023-01-28 02:19 UTC, murata0705 commented on app/models/event.rb
> +  end
メソッドの中身を見ると`only_woman_event`かどうかを判定しているわけでなく、参加できるかどうかを見ているので`participatable?(user)`とかのほうが良いかもです。

2023-01-28 02:20 UTC, murata0705 commented
コードを修正したら、壊れていないか RSpec を実行するようにしましょう。
変更後の状態で再度実行し、テスト結果をこちらにはってください 🙏🏻

2023-01-30 05:14 UTC, haru248 commented on app/models/event.rb
> +  end
[530e6f9](https://github.com/haru248/mokumoku/pull/2/commits/530e6f9532a51bf2b47c945af79be186816b0e77)でメソッド名を変更しました

2023-01-30 05:17 UTC, haru248 commented
了解しました。
こちらメソッド名変更後のrspec実行結果になります。
[![Image from Gyazo](https://i.gyazo.com/591120cb2a00d3b3c508a83639891560.png)](https://gyazo.com/591120cb2a00d3b3c508a83639891560)

2023-01-30 10:20 UTC, busitora approved these changes
LGTM！

2023-01-30 11:07 UTC, merged